### Importing the OpenCV Library

In this step, we import the **OpenCV** library using `import cv2`. OpenCV is a powerful library used for computer vision and image processing tasks. It provides functions to work with images, videos, and many other related operations.

- **`cv2`**: This is the module name used to access OpenCV functions in Python.
- Before using OpenCV, make sure it is installed in your environment by running `pip install opencv-python`.


In [66]:
import cv2 


### Reading an Image

In this step, we use the `cv2.imread()` function from OpenCV to read an image from a file. The function takes the path to the image file as an argument (in this case, `"app.jpg"`) and loads the image into a variable `img`. The image is stored as a NumPy array where each element represents the pixel values (BGR format by default).

If the image is not found, the function returns `None`.

- **Note**: Ensure that the image file `"app.jpg"` exists in the specified path or provide the correct file path.


In [67]:
img = cv2.imread("app.jpg")


### Checking the Type of the Image Object

In this step, we use the `type()` function to check the data type of the `img` object. 

When an image is loaded using OpenCV's `cv2.imread()`, the image is represented as a **NumPy array**. This allows you to manipulate the image data easily, as each pixel is stored as a multi-dimensional array.

- **Expected Output**: If the image is loaded successfully, the output will be `<class 'numpy.ndarray'>`.
- If the image is not loaded properly (e.g., the file path is incorrect), the type will return `NoneType`.


In [68]:
type(img)

numpy.ndarray

In [69]:
img.shape

(4480, 6720, 3)

In [70]:
width,height,channel =img.shape

In [71]:
print(f"The width is : {width} \nThe hight is: {height} \nThe number of channels: {channel} ")

The width is : 4480 
The hight is: 6720 
The number of channels: 3 


In [72]:
cv2.imshow("image1",img)

# Wait for a key press and close the windows
cv2.waitKey(0)
cv2.destroyAllWindows()

In [73]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [74]:
# Split the image into its Blue, Green, and Red channels
B, G, R = cv2.split(img2)

# Print each channel matrix
print("Red Channel Matrix: \n", R)
print("\nGreen Channel Matrix: \n", G)
print("\nBlue Channel Matrix: \n", B)


Red Channel Matrix: 
 [[238 240 237 ... 177 177 177]
 [239 237 237 ... 178 178 177]
 [237 238 237 ... 178 178 177]
 ...
 [113 110 113 ...   4   5   4]
 [ 94 102 110 ...   4   4   4]
 [106 117 116 ...   5   5   5]]

Green Channel Matrix: 
 [[244 244 242 ... 189 189 189]
 [245 242 242 ... 190 190 189]
 [243 242 242 ... 190 190 189]
 ...
 [113 102 101 ...   5   6   5]
 [ 95  94 100 ...   5   5   5]
 [106 107 107 ...   6   6   7]]

Blue Channel Matrix: 
 [[245 246 245 ... 207 208 209]
 [245 243 245 ... 208 209 209]
 [242 242 245 ... 208 209 209]
 ...
 [ 90  89  92 ...   8   9   8]
 [ 73  80  88 ...   8   8   8]
 [ 79  94  95 ...   9   9  10]]


In [75]:
# Optionally, display each channel as an image
cv2.imshow('Red Channel', R)
cv2.imshow('Green Channel', G)
cv2.imshow('Blue Channel', B)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [76]:
img2 = cv2.imread(r"C:\Users\FACULTY\Downloads\Digital image processing Lab notebooks\images\app.jpg")
img2 = cv2.resize(img2, (700,500))

In [77]:
cv2.imshow("image",img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [78]:
img2 = cv2.imread("./images/test_image.png")

In [79]:
cv2.imshow("image",img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [80]:
# Import the necessary libraries
from sklearn.datasets import load_iris
import pandas as pd

# Load the Iris dataset
iris = load_iris()

# Display the dataset's description
print(iris.DESCR)


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [81]:
# Display the dataset's description
print(iris.DESCR)

# Convert the dataset into a pandas DataFrame
# The dataset contains 'data' (features) and 'target' (labels)
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Display the first 5 rows of the DataFrame
print(df.head())



.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========